name: Action Practice


on:
  push:
  schedule:
    - cron: "0 16 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests beautifulsoup4 lxml
      - name: Run
        run: python3 ./script.py
      - name: Configure Git LFS
        run: git lfs install
      - name: Install Git LFS
        run: |
         wget https://github.com/git-lfs/git-lfs/releases/download/v3.0.2/git-lfs-linux-amd64-v3.0.2.tar.gz
         tar -xzf git-lfs-linux-amd64-v3.0.2.tar.gz
         ./git-lfs-3.0.2/install.sh
      - name: Track large files with Git LFS
        run: |
         echo "* filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
         git lfs track "*"
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed master
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          branch: master      

